# Generated by Django 4.2.3 on 2023-08-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_vermudas_bermudas_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reparto',
        ),
    ]
