# Generated by Django 4.2.3 on 2023-08-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_delete_reparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='buzos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
